cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED FLU_SOURCE_DIR OR NOT DEFINED FLU_BUILD_DIR)
    message(FATAL_ERROR "Use make fakeroot from the project directory.")
endif()
file(REAL_PATH "${FLU_SOURCE_DIR}" source)
file(REAL_PATH "${FLU_BUILD_DIR}" build BASE_DIRECTORY "${source}")
set(destination "${source}/fakeroot")
if(NOT EXISTS "${source}/.PKGINFO")
    message(FATAL_ERROR "Missing package metadata: ${source}/.PKGINFO")
endif()
if(IS_SYMLINK "${destination}" OR
   (EXISTS "${destination}" AND NOT IS_DIRECTORY "${destination}"))
    message(FATAL_ERROR "Refusing to replace fakeroot: it must be a real directory, not a symlink or file.")
endif()
# Never move/remove the active build tree while replacing a packaging tree.
cmake_path(IS_PREFIX destination "${build}" NORMALIZE build_in_destination)
if(build_in_destination OR build STREQUAL source)
    message(FATAL_ERROR "BUILD_DIR must be separate from the source directory and outside fakeroot/.")
endif()

file(READ "${source}/.PKGINFO" metadata)
foreach(field builddate size)
    string(REGEX MATCHALL "(^|\n)${field} = [^\n]*" fields "${metadata}")
    list(LENGTH fields count)
    if(NOT count EQUAL 1 OR NOT fields MATCHES " = [0-9]+$")
        message(FATAL_ERROR ".PKGINFO must contain exactly one numeric ${field} field.")
    endif()
endforeach()
if(FLU_VALIDATE_ONLY)
    return()
endif()

# Build a fresh tree first. A failed install never destroys the previous one.
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
set(staging "${source}/.fakeroot-stage-${suffix}")
set(previous "${source}/.fakeroot-previous-${suffix}")
file(MAKE_DIRECTORY "${staging}")
execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env "DESTDIR=${staging}"
        "${CMAKE_COMMAND}" --install "${build}" --prefix /usr --config Release
    RESULT_VARIABLE installed)
if(NOT installed STREQUAL "0")
    file(REMOVE_RECURSE "${staging}")
    message(FATAL_ERROR "Staging failed; the previous fakeroot was left unchanged.")
endif()

# Copy the maintained package identity, version and dependencies. Only generated
# fields change; metadata is not counted as installed payload. Do not follow
# symlinks out of the package tree when measuring its regular files.
set(size 0)
file(GLOB_RECURSE payload LIST_DIRECTORIES FALSE "${staging}/*")
foreach(path IN LISTS payload)
    if(NOT IS_SYMLINK "${path}")
        file(SIZE "${path}" bytes)
        math(EXPR size "${size} + ${bytes}")
    endif()
endforeach()
string(TIMESTAMP builddate "%s" UTC)
string(REGEX REPLACE "(^|\n)builddate = [0-9]+" "\\1builddate = ${builddate}" metadata "${metadata}")
string(REGEX REPLACE "(^|\n)size = [0-9]+" "\\1size = ${size}" metadata "${metadata}")
file(WRITE "${staging}/.PKGINFO" "${metadata}")

if(EXISTS "${destination}")
    file(RENAME "${destination}" "${previous}" RESULT moved)
    if(NOT moved STREQUAL "0")
        file(REMOVE_RECURSE "${staging}")
        message(FATAL_ERROR "Could not preserve the previous fakeroot: ${moved}")
    endif()
endif()
file(RENAME "${staging}" "${destination}" RESULT published)
if(NOT published STREQUAL "0")
    if(EXISTS "${previous}")
        file(RENAME "${previous}" "${destination}" RESULT restored)
        if(NOT restored STREQUAL "0")
            message(FATAL_ERROR "Staging failed. Previous output is preserved at ${previous}")
        endif()
    endif()
    file(REMOVE_RECURSE "${staging}")
    message(FATAL_ERROR "Could not publish fakeroot: ${published}")
endif()
if(EXISTS "${previous}")
    file(REMOVE_RECURSE "${previous}")
endif()
message(STATUS "Package files ready in ${destination}, including .PKGINFO (${size} bytes of payload).")
